spring: 
  sql:
    init:
      mode: always
      schema-locations: classpath:schema.sql
        
store:
  datasource:
    mysql:
      driver-class-name: com.mysql.cj.jdbc.Driver
      password: cicd_password
      jdbc-url: jdbc:mysql://localhost:3306/store
      username: root    
logging:
  level:
    org:
      springframework:
        jdbc:
         core: TRACE        